/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MidLet;

public class MidLet {
  public static Integer getLength(String word){
    int len = word.length();
    if (len == 0){
      return 0;
    }
    else if (len == 1) {
      return 1;
    } 
    else if (len == 2) {
      return 2;
    }
    else if (len % 2 == 1) {
      return 3;
    }
    else {
      return 4;
    }
  }


  public String getMiddleLetter(String word) {
    Integer i = MidLet.getLength(word);
    int len = word.length();
    switch (i){
      case 0: return "String should have length more than 0";
      case 1: return word;
      case 2: return word;
      case 3:
      String midC= "" + word.charAt((len-1)/2);
      return midC;
      default:
      return word.substring((len)/2-1, (len)/2+1);

    }
  }

  public static void main(String[] args) {
    MidLet wordMid = new MidLet();
    String word = "abcdef";
      System.out.println(wordMid.getMiddleLetter(word));
  }
}
