/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MidLet;

import org.junit.Test;
import static org.junit.Assert.*;

public class MidLetTest {
    @Test public void  testStringLengthGreater0() {
        MidLet word = new MidLet();
        assertEquals("String should have length more than 0", word.getMiddleLetter(""));
    }
    @Test public void  testStringLength1Or2() {
        MidLet word = new MidLet();
        assertEquals("AB", word.getMiddleLetter("AB"));
        assertEquals("A", word.getMiddleLetter("A"));
    }
    @Test public void  testStringOdd() {
        MidLet word = new MidLet();
        assertEquals("B", word.getMiddleLetter("ABC"));
    }
    @Test public void  testStringEven() {
        MidLet word = new MidLet();
        assertEquals("BC", word.getMiddleLetter("ABCD"));
    }

}
