/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import java.util.ArrayList;

public class TodoList {
  ArrayList<String> lst = new ArrayList<String>();

  public void addTodo(String todo) {
    lst.add(todo);
  }
  public ArrayList<String>  get() {
    return lst;
  }


public static void main(String[] args){
  TodoList list = new TodoList();
  list.addTodo("Study Java");
  list.addTodo("Study Python");
  list.addTodo("Study Ruby");

  for(String i: list.get()) {
    System.out.println(i);
  }
}
}

