/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WordGame;

import org.junit.Test;
import static org.junit.Assert.*;

public class WordGameTest {
  @Test public void testGetsWordToGuess() {
    WordGame game = new WordGame("MAKERS");
    assertEquals(game.getWordToGuess(), "M_____");
  }
}
