/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WordGame;

public class WordGame {
  String word;


  public WordGame(String word) {
    this.word = word;

  }
  public String getWordToGuess() {
    StringBuilder builder = new StringBuilder();
    for (int i = 0; i < this.word.length(); i++) {
        Character currentLetter = this.word.charAt(0);
        if (i == 0) {
            builder.append(currentLetter);
        } else {
            builder.append("_");
        }
    }
    return builder.toString();

}


  


    // public String getWordToGuess() {
    //   int len = word.length();
      
    //   return word.charAt(0) + "_".repeat(len-1);
    // }

    public static void main(String[] args) {
      WordGame x = new WordGame("MAKERS");
      System.out.println(x.getWordToGuess());
    }
}
