/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LeapYears;

public class LeapYears {

  public boolean checkLeap(int year) {
    if (year % 400 == 0) {
      return true;
    }
    else if (year % 4 == 0 && year % 100 != 0) {
      return true;
    }
    else {
      return false;
    }  
  }


  public static void main(String[] args){
    LeapYears year = new LeapYears();
    for (int i = 1900; i < 2030; i++) {
      boolean result = year.checkLeap(i);
      if (result == true){
        System.out.printf("The year %d is leap\n", i);
      }
      else {
        System.out.printf("The year %d is not leap\n", i);
      }

    }

  }
 
}
